# Generated by Django 4.0.3 on 2022-03-17 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_alter_car_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinstance',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderinstance',
            name='service_id',
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=200, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='orderinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for this Order Instance.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of a service provided.', max_length=200, verbose_name='Name'),
        ),
    ]
