# Generated by Django 4.0.3 on 2022-03-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0005_alter_orderinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='orderinstance',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Accepted'), (2, 'Complited'), (3, 'Declined')], db_index=True, default=0, verbose_name='Status'),
        ),
    ]
