# Generated by Django 4.0.3 on 2022-03-20 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisas', '0006_car_image_alter_orderinstance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at', 'client'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='orderinstance',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderinstance',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderinstance',
            name='due_back',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due back'),
        ),
    ]
