# Generated by Django 4.0.3 on 2022-03-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0008_car_description_alter_orderinstance_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due back'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Accepted'), (2, 'Complited'), (3, 'Declined')], db_index=True, default=0, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservisas.order', verbose_name='Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservisas.service', verbose_name='Service')),
            ],
        ),
    ]
