# Generated by Django 4.0.3 on 2022-03-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0009_order_due_back_order_status_orderline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at', 'car'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderline',
            name='due_back',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due back'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Accepted'), (2, 'Complited'), (3, 'Declined')], db_index=True, default=0, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='OrderInstance',
        ),
    ]
