# Generated by Django 4.0.3 on 2022-03-23 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0010_alter_order_options_remove_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
