# Generated by Django 4.0.3 on 2022-03-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0012_alter_orderline_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Accepted'), (2, 'Complited'), (3, 'Declined')], db_index=True, default=0, verbose_name='Status')),
                ('due_back', models.DateField(blank=True, db_index=True, null=True, verbose_name='Due back')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='status',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
