# Generated by Django 4.0.3 on 2022-03-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0014_delete_orderinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due back'),
        ),
    ]
