# Generated by Django 4.0.3 on 2022-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0015_order_due_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'New'), (1, 'Accepted'), (2, 'Declined')], default=0, verbose_name='Status'),
        ),
    ]
