# Generated by Django 4.0.3 on 2022-03-26 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisas', '0018_alter_car_image_ordercomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Comment', 'verbose_name_plural': 'Order Comments'},
        ),
        migrations.AddField(
            model_name='ordercomment',
            name='reply',
            field=tinymce.models.HTMLField(default='', max_length=1000, verbose_name='Reply'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='autoservisas.order'),
        ),
    ]
